persona_def_tests = [
  [
    "persona",
    "nombre_persona",
    "input",
    1,
    "comprobar tamaño minimo",
    "min_size",
    "ADD",
    "nombre_persona_min_size_KO",
    "El nombre de usuario es muy corto, introduzca por lo menos 3 caracteres",
  ],
  [
    "persona",
    "nombre_persona",
    "input",
    2,
    "comprobar tamaño máximo",
    "max_size",
    "ADD",
    "nombre_persona_max_size_KO",
    "El nombre de usuario es muy largo, introduzca un máximo de 45 caracteres",
  ],
  [
    "persona",
    "nombre_persona",
    "input",
    3,
    "comprobar carácteres válidos",
    "format",
    "ADD",
    "nombre_persona_format_KO",
    "El nombre de usuario contiene caracteres nó validos, elimine caracteres no pertenecientes al alfabeto, espacios, guiones o puntos",
  ],
  [
    "persona",
    "nombre_persona",
    "input",
    4,
    "comprobar valicidad nombre",
    "format",
    "ADD",
    true,
    "",
  ],
];
persona_pruebas = [
  [
    "persona",
    "nombre_persona",
    1,
    1,
    "ADD",
    { nombre_persona: "aa" },
    "nombre_persona_min_size_KO",
  ],
  [
    "persona",
    "nombre_persona",
    2,
    2,
    "ADD",
    { nombre_persona: "a.repeat(46)" },
    "nombre_persona_inva",
  ],
  [
    "persona",
    "nombre_persona",
    3,
    3,
    "ADD",
    { nombre_persona: "abcde__^" },
    "nombre_persona_format_KO",
  ],
  [
    "persona",
    "nombre_persona",
    4,
    4,
    "ADD",
    { nombre_persona: "abcdefghijklmnñopqrstuvwxyzáZA-. " },
    true,
  ],
];
